### ISSUE TITLE
README incorrect

### ISSUE THREAD

**Issue by fvanroie** [nagyrobi/files#1]
From the README.md:

> These can't be included directly whith alphanumeric fonts in the same file because their location on the codeplane starts way up at F0001 which cannot be addressed by hasp-lvgl.

That statement is not correct. lvgl, and hence hasp-lvgl, allows for 65535 glyphs in range 0x0 to 0xFFFFFFFF.

**Comment by nagyrobi** [comment]
My experience shows that glyphs above F0001 don't display. The only way to make them appear was to bring them below that number.

**Comment by fvanroie** [comment]
What exactly did you try to include F0001 icons? 
Rather then shifting glyphs, I'm trying to understand what is the exact problem here.

**Comment by nagyrobi** [comment]
Sorry my mistake: it's not 0xF0001 but 0x10000. I remembered wrong when I wrote the readme. Fixed, thanks.
MDI icons start at 0xf0001 anyway.

Multiple issues occured.
To try to combine MDI icons with Roboto fonts, here's what I did:
- use the official font converter from https://lvgl.io/tools/fontconverter
- use the official RobotoCondensed-Regular TTF font
- pick the range "0x020,0x021,0x02B-0x02E,0x030-0x03A,0x03F,0x020,0x021,0x025,0x028-0x03A,0x03C-0x05B,0x05D,0x05F,0x061-0x07A,0x07C,0x0B0,0x0B1,0x0B5,0x0B7,0x0BC-0x0BE"
- use the MDI TTF font from https://materialdesignicons.com/
- pick some icons, like range "0xF0335,0xF0336,0xF111C,0xF111E,0xF09DD,0xF09D7,0xF02DC,0xF004D,0xF0054,0xF0731,0xF0734,0xF0140,0xF0143,0xF005D,0xF0045,0xF04DB"
- Error: Codepoint delta out of range occurs

However if you don't want to combine with normal font, you can render a .c file only with MDI icons with the range above, however they won't be displayed in hasp-lvgl on lanbon l8.

My next step was to shift down the codes to F000 (where the Microsoft Symbols usually start). Range was like "0xF044,0xF05C,0xF04C,0xF053,0xF13F,0xF140,0xF141,0xF142,0xF334,0xF335,0xF437,0xFAD6,0xFAD7,0xF7BF,0xF6C2,0xF6C0,0xF6C1,0xF6D8,0xF6D9,0x1011B,0x1011C,0x1011D,0xF4DA,0xF6A0,0xF35C"

This was still generating Codepoint delta error when combined with regular font, however, the icons from the generated .c file containing only these displayed as long as their value was less than 0x10000. For example 0x1011B did not display, while 0xF044 displayed OK.

The next step was to shift everything way down below to 0x21. Combining doesn't make any sense at this stage, the icons from the generated .c file display well. Range is like "0x0065,0x007d,0x006d,0x0074,0x0160,0x0161,0x0162,0x0163,0x0355,0x0356,0x0458,0x0af7,0x0af8,0x07e0,0x06e3,0x06e1,0x06e2,0x06f9,0x06fa,0x113c,0x113d,0x113e,0x06c1,0x037d,0x037e,0x037f,0x0380,0x042e,0x042a,0x0404,0x04fb,0x0231,0x047f,0x04cd,0x04ce,0x077a,0x059e,0x059f,0x05a0,0x077f,0x038c,0x038d,0x0435,0x0394,0x083b,0x10cf,0x083c,0x0228"

**Comment by nagyrobi** [comment]
I can share the TTF with the glyphs shifted down if you'd like.

Of course a proper selection can be made also by cherry-picking the icons and place them at new locations one by one and thus could be combined like fontawesome, that requires some more work and some discussions, like which address space should we use then.

But maybe it doesn't worth the effort, if we had a properly documented way to make .zi. Addressing could still be an issue though.

**Comment by fvanroie** [comment]
You should give the lv_font_conv tool a try. Reading the docs, it supports glyphs above 0x10000 too.

**Comment by nagyrobi** [comment]
Afaik it's the tool behind https://lvgl.io/tools/fontconverter too.

**Comment by fvanroie** [comment]
Yes but it says that it _does_ support 0x10000 characters, so the statement that lvgl doesn't support it still seems to be incorrect.
Maybe it's a bug in the website, or the tool... I dunno.

**Comment by nagyrobi** [comment]
It does as long is it's not combined with lower values. It can generate a .c file with glyps all above 0x10000 but what's the use of that...
Lvgl builds fine with such a font file but doesn't display it.

**Comment by fvanroie** [comment]
That sounds more like an issue with the utf-8 encoding of the characters then with lvgl imho...

**Comment by nagyrobi** [comment]
The error is glyph [not found](https://github.com/nagyrobi/files/issues/1#issuecomment-808405926) when value is above 0x10000.
Everything works as long as glyphs are under 0xFFFF.

**Comment by fvanroie** [comment]
OK, so you *concluded* that it *must* be an issue in hasp-lvgl at that point?

**Comment by nagyrobi** [comment]
No, I just listed my observations, based on my trial-and-error experiments.

**Comment by fvanroie** [comment]
> 
> 
> The error is glyph [not found](https://github.com/nagyrobi/files/issues/1#issuecomment-808405926) when value is above 0x10000.
> Everything works as long as glyphs are under 0xFFFF.

I filed an issue in the lv_font_conv repo for this lvgl/lv_font_conv#62

**Comment by nagyrobi** [comment]
Thank you.
